"""
reservoir.integrations._trl_staleness — Which replayed rows to train on, and with what weight.

A replayed row was generated by an older policy. How much to trust it is a
decision the buffer makes per row, from quantities the attestation log
records, so that the independent checker can replay every decision:

- the row's **sequence log-ratio** ``r`` (current minus stored behaviour
  logprobs, summed over its tokens), a measurement written to the log as a
  ``float.hex()`` string;
- its exact **importance weight** ``w`` from the sample record;
- its **age** in model versions, recomputed by the checker from the live
  slots;
- the training **row** and **group** it would fill.

``StalenessPolicy`` has four stages, applied in this fixed order and
nowhere else:

0. a non-finite log-ratio is declined (reason ``drift``); nothing below
   can compare it;
1. **age bound**: ``age > max_age`` declines the row (reason ``age``);
2. **ESS floor**: over the rows still kept, the exact effective sample
   size ``(Σw)²/Σw²`` must be at least ``ess_floor`` times their count;
   while it is not, the kept row with the largest ``|r|`` is declined
   (reason ``ess``; ties go to the lower draw position). One kept row
   always satisfies the floor, so this terminates;
3. **group-mass cap**: for each training group that still receives rows,
   the group's importance mass ``Σ w·exp(r)`` over those rows may not
   exceed ``(1 + mass_cap)`` times their count (the mass fresh rows in
   those slots would carry). When it does, every kept row of the group has
   its advantage multiplied by the exact fraction ``cap / mass``;
4. **legacy gate**: ``|r| > max_log_ratio`` declines the row (reason
   ``drift``), as the 0.6.0 drift gate did. It runs last so a log written
   with the gate alone reads the same as before; a row it declines was
   counted in its group's mass in stage 3.

More than ``max_declines_per_step`` declines in one step raise instead of
continuing, because a policy that quietly drops the only informative rows
would hide a collapsed reward signal.

Exactness. Every comparison above is exact: the weights are rationals,
the floor and the cap are the exact values of their binary64 settings, and
``|r|`` comparisons are on the recorded floats. The one transcendental,
``exp(r)``, is computed by ``exact_exp`` with Python's ``decimal`` module
at a fixed precision, which is correctly rounded and therefore identical
on every platform, and frozen to a ``Fraction``; ``r`` is clamped to
``±LOG_RATIO_CLAMP`` first so the fraction stays a few hundred digits. The
checker (``reservoir_checker.staleness``) carries its own copy of the same
arithmetic and must not import this module.

Presets: ``conservative`` (age 16, floor 0.5, cap 0.25), ``async`` (age
64, floor 0.3, cap 0.5), ``off`` (nothing on; today's behaviour).
"""

from __future__ import annotations

import dataclasses
import decimal
import math
from dataclasses import dataclass
from fractions import Fraction
from typing import Final, NamedTuple, Optional, Sequence, Union

EXP_DIGITS: Final[int] = 30
"""Significant decimal digits of ``exact_exp``; the checker uses the same constant."""

LOG_RATIO_CLAMP: Final[float] = 700.0
"""``exp`` is evaluated at ``min(max(r, -clamp), clamp)``: beyond it float64 overflows and the fraction would be unbounded."""

DECLINE_REASONS: Final[tuple[str, ...]] = ("drift", "age", "ess")
"""Why a row was declined; ``drift`` and ``age`` evict the entry, ``ess`` does not (the batch, not the row, was the problem)."""

EVICTING_REASONS: Final[frozenset[str]] = frozenset({"drift", "age"})

_PRESET_VALUES: Final[dict[str, dict]] = {
    "conservative": dict(max_age=16, ess_floor=0.5, mass_cap=0.25),
    "async": dict(max_age=64, ess_floor=0.3, mass_cap=0.5),
    "off": {},
}


_EXP_CONTEXT: Final[decimal.Context] = decimal.Context(
    prec=EXP_DIGITS, Emax=1000, Emin=-1000, rounding=decimal.ROUND_HALF_EVEN,
    traps=[decimal.InvalidOperation, decimal.Overflow, decimal.DivisionByZero],
)
"""A context of its own, so a host application's thread-local decimal traps cannot change the result."""


def exact_exp(r: float) -> Fraction:
    """``exp(r)`` as an exact fraction, correctly rounded to ``EXP_DIGITS`` digits, after clamping ``r``."""
    if not math.isfinite(r):
        raise ValueError(f"exact_exp needs a finite log-ratio, got {r!r}")
    r = min(max(float(r), -LOG_RATIO_CLAMP), LOG_RATIO_CLAMP)
    return Fraction(_EXP_CONTEXT.exp(decimal.Decimal(r)))


def _optional_int(value: Optional[int], name: str) -> Optional[int]:
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise ValueError(f"{name} must be a non-negative int or None, got {value!r}")
    return value


def _optional_float(value: Optional[float], name: str, low: float, low_inclusive: bool, high: Optional[float]) -> Optional[float]:
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError(f"{name} must be a finite number or None, got {value!r}")
    value = float(value)
    if value < low or (value == low and not low_inclusive) or (high is not None and value > high):
        bound = f"{'[' if low_inclusive else '('}{low}, {high if high is not None else 'inf'}]"
        raise ValueError(f"{name} must lie in {bound}, got {value!r}")
    return value


@dataclass(frozen=True)
class StalenessPolicy:
    """The declared rule for replayed rows; see the module docstring for the stages."""

    max_age: Optional[int] = None
    ess_floor: Optional[float] = None
    mass_cap: Optional[float] = None
    max_log_ratio: Optional[float] = None
    max_declines_per_step: Optional[int] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "max_age", _optional_int(self.max_age, "max_age"))
        object.__setattr__(self, "ess_floor", _optional_float(self.ess_floor, "ess_floor", 0.0, False, 1.0))
        object.__setattr__(self, "mass_cap", _optional_float(self.mass_cap, "mass_cap", 0.0, True, None))
        object.__setattr__(self, "max_log_ratio", _optional_float(self.max_log_ratio, "max_log_ratio", 0.0, False, None))
        object.__setattr__(self, "max_declines_per_step", _optional_int(self.max_declines_per_step, "max_declines_per_step"))

    @classmethod
    def preset(cls, name: str) -> "StalenessPolicy":
        """``conservative``, ``async`` or ``off``."""
        if name not in _PRESET_VALUES:
            raise ValueError(f"unknown staleness preset {name!r}; choose one of {sorted(_PRESET_VALUES)}")
        return cls(**_PRESET_VALUES[name])

    @property
    def active(self) -> bool:
        """Whether any stage is configured; an inactive policy records nothing and declines nothing."""
        return any(v is not None for v in (self.max_age, self.ess_floor, self.mass_cap, self.max_log_ratio))

    @property
    def legacy_only(self) -> bool:
        """Only the 0.6.0 drift gate is on."""
        return self.max_log_ratio is not None and all(v is None for v in (self.max_age, self.ess_floor, self.mass_cap))

    def to_record(self, group_size: Optional[int]) -> dict:
        """The ``policy`` field of a telemetry record: ints as ints, floats as ``float.hex()``, absent stages ``None``.

        ``group_size`` is the number of training rows per prompt group when
        groups are contiguous blocks (TRL), so the checker can derive each
        decision's group from its row; ``None`` when the adapter declares
        the groups itself (verl, whose rows may be reordered).
        """
        return {
            "max_age": self.max_age,
            "ess_floor": None if self.ess_floor is None else self.ess_floor.hex(),
            "mass_cap": None if self.mass_cap is None else self.mass_cap.hex(),
            "max_log_ratio": None if self.max_log_ratio is None else self.max_log_ratio.hex(),
            "max_declines_per_step": self.max_declines_per_step,
            "group_size": _optional_int(group_size, "group_size"),
        }

    @classmethod
    def from_record(cls, record: dict) -> "StalenessPolicy":
        def hex_or_none(name: str) -> Optional[float]:
            value = record.get(name)
            return None if value is None else float.fromhex(value)
        return cls(
            max_age=record.get("max_age"), ess_floor=hex_or_none("ess_floor"), mass_cap=hex_or_none("mass_cap"),
            max_log_ratio=hex_or_none("max_log_ratio"), max_declines_per_step=record.get("max_declines_per_step"),
        )


PRESETS: Final[dict[str, StalenessPolicy]] = {name: StalenessPolicy.preset(name) for name in _PRESET_VALUES}


@dataclass(frozen=True)
class RowDecision:
    """What the policy decided for one draw of the sampled batch."""

    draw: int                   # position in the sample record
    row: int                    # training-batch row it would fill
    group: int                  # training group of that row
    reason: Optional[str]       # None when kept, else one of DECLINE_REASONS
    scale: Fraction             # multiplies the kept row's weighted advantage; 1 unless the mass cap bound

    @property
    def kept(self) -> bool:
        return self.reason is None

    def to_record(self) -> dict:
        return {"draw": self.draw, "row": self.row, "group": self.group, "reason": self.reason,
                "scale_num": str(self.scale.numerator), "scale_den": str(self.scale.denominator)}


def _check_inputs(ratios, is_weights, ages, rows, groups) -> None:
    n = len(ratios)
    if not (len(is_weights) == len(ages) == len(rows) == len(groups) == n):
        raise ValueError("decide: ratios, is_weights, ages, rows and groups must have the same length")
    if len(set(rows)) != n:
        raise ValueError(f"decide: rows must be distinct, got {list(rows)}")
    if any(isinstance(a, bool) or not isinstance(a, int) or a < 0 for a in ages):
        raise ValueError(f"decide: every age must be a non-negative int, got {list(ages)}")
    if any(not isinstance(w, Fraction) or w <= 0 for w in is_weights):
        raise ValueError("decide: every importance weight must be a positive Fraction")


def ess_of(weights: Sequence[Fraction]) -> Fraction:
    """``(Σw)² / Σw²``, exact."""
    total = sum(weights, Fraction(0))
    return total * total / sum((w * w for w in weights), Fraction(0))


def decide(
    policy: StalenessPolicy, *, ratios: Sequence[float], is_weights: Sequence[Fraction], ages: Sequence[int],
    rows: Sequence[int], groups: Sequence[int],
) -> tuple[RowDecision, ...]:
    """Apply ``policy`` to one sampled batch; one decision per draw, in draw order; ``()`` when the policy is inactive.

    Raises ``RuntimeError`` when more than ``max_declines_per_step`` rows
    would be declined, before anything is returned.
    """
    _check_inputs(ratios, is_weights, ages, rows, groups)
    if not policy.active:
        return ()
    n = len(ratios)
    reasons: list[Optional[str]] = [None if math.isfinite(r) else "drift" for r in ratios]   # stage 0
    if policy.max_age is not None:                                                            # stage 1
        for k in range(n):
            if reasons[k] is None and ages[k] > policy.max_age:
                reasons[k] = "age"
    if policy.ess_floor is not None:                                                          # stage 2
        floor = Fraction(policy.ess_floor)
        kept = [k for k in range(n) if reasons[k] is None]
        total = sum((is_weights[k] for k in kept), Fraction(0))
        squares = sum((is_weights[k] * is_weights[k] for k in kept), Fraction(0))
        while len(kept) > 1 and total * total < floor * len(kept) * squares:   # ESS/n < floor, cross-multiplied
            victim = max(kept, key=lambda k: (abs(ratios[k]), -k))
            reasons[victim] = "ess"
            kept.remove(victim)
            total -= is_weights[victim]
            squares -= is_weights[victim] * is_weights[victim]
    scales = [Fraction(1)] * n
    if policy.mass_cap is not None:                                                           # stage 3
        cap_per_row = 1 + Fraction(policy.mass_cap)
        members: dict[int, list[int]] = {}
        for k in range(n):
            if reasons[k] is None:
                members.setdefault(groups[k], []).append(k)
        for ks in members.values():
            mass = sum((is_weights[k] * exact_exp(ratios[k]) for k in ks), Fraction(0))
            cap = cap_per_row * len(ks)
            if mass > cap:
                for k in ks:
                    scales[k] = cap / mass
    if policy.max_log_ratio is not None:                                                      # stage 4
        for k in range(n):
            if reasons[k] is None and abs(ratios[k]) > policy.max_log_ratio:
                reasons[k] = "drift"
                scales[k] = Fraction(1)
    declined = sum(1 for r in reasons if r is not None)
    if policy.max_declines_per_step is not None and declined > policy.max_declines_per_step:
        raise RuntimeError(
            f"the staleness policy would decline {declined} of {n} replayed rows this step, above "
            f"max_declines_per_step={policy.max_declines_per_step}; the buffer may have gone stale or the policy moved far"
        )
    return tuple(RowDecision(k, int(rows[k]), int(groups[k]), reasons[k], scales[k]) for k in range(n))


__all__ = [
    "DECLINE_REASONS",
    "EVICTING_REASONS",
    "EXP_DIGITS",
    "LOG_RATIO_CLAMP",
    "PRESETS",
    "RowDecision",
    "StalenessPolicy",
    "decide",
    "ess_of",
    "exact_exp",
]


# ---------------------------------------------------------------------------
# Adapter helpers: from a policy and a sampled batch to what gets written
# ---------------------------------------------------------------------------

class Placement(NamedTuple):
    """Which draws of a sampled batch are placed, declined, and with what advantage."""

    kept: list[int]           # draw positions placed, in draw order
    declined: list[int]       # draw positions declined, in draw order
    weighted: list[float]     # advantage written for each kept draw: reward * float(is_weight * scale)
    rescaled: int             # kept draws whose scale is below 1


def resolve_policy(
    staleness_policy: Union[StalenessPolicy, str, None], max_log_ratio: Optional[float],
    max_declines_per_step: Optional[int], telemetry: bool,
) -> StalenessPolicy:
    """The adapter's policy from its constructor arguments.

    ``staleness_policy`` is a ``StalenessPolicy``, a preset name or None;
    the legacy ``max_log_ratio`` and ``max_declines_per_step`` keywords fill
    the policy's stage 4 when it does not set them itself, and conflict
    otherwise. Stages 1 to 3 record their decisions in the telemetry
    record, so they need ``telemetry=True``; the legacy gate alone keeps
    working with telemetry off, as in 0.6.0 (its declines are then visible
    only in the batch witness).
    """
    if isinstance(staleness_policy, str):
        policy = StalenessPolicy.preset(staleness_policy)
    elif staleness_policy is None:
        policy = StalenessPolicy()
    elif isinstance(staleness_policy, StalenessPolicy):
        policy = staleness_policy
    else:
        raise TypeError(f"staleness_policy must be a StalenessPolicy, a preset name or None, got {type(staleness_policy).__name__}")
    for name, value in (("max_log_ratio", max_log_ratio), ("max_declines_per_step", max_declines_per_step)):
        if value is None:
            continue
        if getattr(policy, name) is not None:
            raise ValueError(f"{name} is set both as a keyword and on the staleness policy; set it in one place")
        policy = dataclasses.replace(policy, **{name: value})
    if policy.active and not policy.legacy_only and not telemetry:
        raise ValueError(
            "a staleness policy with an age bound, ESS floor or mass cap records its decisions in the telemetry "
            "record and needs telemetry=True; only the legacy max_log_ratio gate runs with telemetry off"
        )
    return policy


def place(rewards: Sequence[float], is_weights: Sequence[Fraction], decisions: Sequence[RowDecision]) -> Placement:
    """Fold the decisions into the kept and declined draws and the advantages to write.

    With no decisions (an inactive policy) every draw is kept with its
    importance-weighted advantage, exactly as before the policy existed.
    """
    n = len(rewards)
    if not decisions:
        return Placement(list(range(n)), [], [float(r) * float(w) for r, w in zip(rewards, is_weights)], 0)
    if len(decisions) != n:
        raise ValueError(f"{len(decisions)} decisions for {n} draws")
    kept = [d.draw for d in decisions if d.kept]
    declined = [d.draw for d in decisions if not d.kept]
    weighted = [float(rewards[d.draw]) * float(is_weights[d.draw] * d.scale) for d in decisions if d.kept]
    return Placement(kept, declined, weighted, sum(1 for d in decisions if d.kept and d.scale != 1))


def evictions_for(indices: Sequence[int], decisions: Sequence[RowDecision]) -> list[tuple[int, str]]:
    """``(slot, reason)`` for every buffer slot whose draws were all declined for an evicting reason.

    A slot drawn more than once is evicted only if no draw of it was kept;
    an ``ess`` decline never evicts (the batch, not the row, was the
    problem). When one slot was declined as both ``drift`` and ``age``,
    ``drift`` is recorded.
    """
    kept_slots = {indices[d.draw] for d in decisions if d.kept}
    reasons: dict[int, str] = {}
    for d in decisions:
        slot = indices[d.draw]
        if d.reason in EVICTING_REASONS and slot not in kept_slots:
            reasons[slot] = "drift" if "drift" in (reasons.get(slot), d.reason) else d.reason
    return sorted(reasons.items())


__all__ += ["Placement", "evictions_for", "place", "resolve_policy"]
